package pe.pucp.plg.dto.enums;

public enum EventType {
    SIMULATION_STARTED,
    SIMULATION_COMPLETED,
    SIMULATION_COLLAPSED,
    TRUCK_STATE_UPDATED,
    TRUCK_POSITION_UPDATED,
    ORDER_STATE_UPDATED,
    TANK_LEVEL_UPDATED,
    ROUTE_ASSIGNED,
    ACTION_STARTED,
    ACTION_COMPLETED
}
